export enum Section {
  Education = "education",
  Experience = "experience",
  Portfolio = "portfolio",
  Publication = "publication",
  News = "news",
  Skill = "Skill",
  Speech = "speech",
  TeachingAssistant = "teaching-assistant",
  Intern = "intern",
  Award = "award",
  AcademicSociety = "academic-society",
  ResearchAssistant = "research-assistant",
  Qualification = "qualification",
  Community = "community",
  Outreach = "outreach",
  Keyword = "keyword",
}

export const sectionOrder = [
  Section.News,
  Section.Skill,
  Section.Keyword,
  Section.Publication,
  Section.Speech,
  Section.Education,
  Section.Experience,
  Section.Intern,
  Section.ResearchAssistant,
  Section.Award,
  Section.Community,
  Section.Outreach,
  Section.TeachingAssistant,
  Section.Qualification,
  Section.AcademicSociety,
  Section.Portfolio,
];
